apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: demo
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: awssm-secret
    kind: SecretStore
  target:
    name: kube-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: name-of-secrets-in-secrets-manager
